#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_core_user_login:
    path:  /login
    controller: App\Controller\SecurityController::login
   

_core_user_logout:
    path:  /user/logout
    controller: App\Controller\SecurityController::logout
   

_core_user_login_check:
    path:  /login_check